<?php
/**
 * QEmailMessage
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  sendpost
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace sendpost\model;

use \ArrayAccess;
use \sendpost\ObjectSerializer;

/**
 * QEmailMessage Class Doc Comment
 *
 * @category Class
 * @package  sendpost
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class QEmailMessage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'QEmailMessage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'int',
        'amp_body' => 'string',
        'attachments' => '\sendpost\model\Attachment[]',
        'attempt' => 'int',
        'custom_fields' => 'object',
        'email_type' => 'string',
        'from' => '\sendpost\model\From',
        'groups' => 'string[]',
        'header_bcc' => '\sendpost\model\CopyTo[]',
        'header_cc' => '\sendpost\model\CopyTo[]',
        'header_to' => '\sendpost\model\To',
        'headers' => 'object',
        'html_body' => 'string',
        'ip_id' => 'int',
        'ip_pool' => 'string',
        'local_ip' => 'string',
        'message_id' => 'string',
        'pre_text' => 'string',
        'public_ip' => 'string',
        'reply_to' => '\sendpost\model\ReplyTo',
        'sub_account_id' => 'int',
        'subject' => 'string',
        'submitted_at' => 'int',
        'text_body' => 'string',
        'to' => '\sendpost\model\To',
        'track_clicks' => 'bool',
        'track_opens' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => 'int64',
        'amp_body' => null,
        'attachments' => null,
        'attempt' => 'int64',
        'custom_fields' => null,
        'email_type' => null,
        'from' => null,
        'groups' => null,
        'header_bcc' => null,
        'header_cc' => null,
        'header_to' => null,
        'headers' => null,
        'html_body' => null,
        'ip_id' => 'int64',
        'ip_pool' => null,
        'local_ip' => null,
        'message_id' => null,
        'pre_text' => null,
        'public_ip' => null,
        'reply_to' => null,
        'sub_account_id' => 'int64',
        'subject' => null,
        'submitted_at' => 'int64',
        'text_body' => null,
        'to' => null,
        'track_clicks' => null,
        'track_opens' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_id' => false,
		'amp_body' => false,
		'attachments' => false,
		'attempt' => false,
		'custom_fields' => false,
		'email_type' => false,
		'from' => false,
		'groups' => false,
		'header_bcc' => false,
		'header_cc' => false,
		'header_to' => false,
		'headers' => false,
		'html_body' => false,
		'ip_id' => false,
		'ip_pool' => false,
		'local_ip' => false,
		'message_id' => false,
		'pre_text' => false,
		'public_ip' => false,
		'reply_to' => false,
		'sub_account_id' => false,
		'subject' => false,
		'submitted_at' => false,
		'text_body' => false,
		'to' => false,
		'track_clicks' => false,
		'track_opens' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountID',
        'amp_body' => 'ampBody',
        'attachments' => 'attachments',
        'attempt' => 'attempt',
        'custom_fields' => 'customFields',
        'email_type' => 'emailType',
        'from' => 'from',
        'groups' => 'groups',
        'header_bcc' => 'headerBcc',
        'header_cc' => 'headerCc',
        'header_to' => 'headerTo',
        'headers' => 'headers',
        'html_body' => 'htmlBody',
        'ip_id' => 'ipID',
        'ip_pool' => 'ipPool',
        'local_ip' => 'localIP',
        'message_id' => 'messageID',
        'pre_text' => 'preText',
        'public_ip' => 'publicIP',
        'reply_to' => 'replyTo',
        'sub_account_id' => 'subAccountID',
        'subject' => 'subject',
        'submitted_at' => 'submittedAt',
        'text_body' => 'textBody',
        'to' => 'to',
        'track_clicks' => 'trackClicks',
        'track_opens' => 'trackOpens'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'amp_body' => 'setAmpBody',
        'attachments' => 'setAttachments',
        'attempt' => 'setAttempt',
        'custom_fields' => 'setCustomFields',
        'email_type' => 'setEmailType',
        'from' => 'setFrom',
        'groups' => 'setGroups',
        'header_bcc' => 'setHeaderBcc',
        'header_cc' => 'setHeaderCc',
        'header_to' => 'setHeaderTo',
        'headers' => 'setHeaders',
        'html_body' => 'setHtmlBody',
        'ip_id' => 'setIpId',
        'ip_pool' => 'setIpPool',
        'local_ip' => 'setLocalIp',
        'message_id' => 'setMessageId',
        'pre_text' => 'setPreText',
        'public_ip' => 'setPublicIp',
        'reply_to' => 'setReplyTo',
        'sub_account_id' => 'setSubAccountId',
        'subject' => 'setSubject',
        'submitted_at' => 'setSubmittedAt',
        'text_body' => 'setTextBody',
        'to' => 'setTo',
        'track_clicks' => 'setTrackClicks',
        'track_opens' => 'setTrackOpens'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'amp_body' => 'getAmpBody',
        'attachments' => 'getAttachments',
        'attempt' => 'getAttempt',
        'custom_fields' => 'getCustomFields',
        'email_type' => 'getEmailType',
        'from' => 'getFrom',
        'groups' => 'getGroups',
        'header_bcc' => 'getHeaderBcc',
        'header_cc' => 'getHeaderCc',
        'header_to' => 'getHeaderTo',
        'headers' => 'getHeaders',
        'html_body' => 'getHtmlBody',
        'ip_id' => 'getIpId',
        'ip_pool' => 'getIpPool',
        'local_ip' => 'getLocalIp',
        'message_id' => 'getMessageId',
        'pre_text' => 'getPreText',
        'public_ip' => 'getPublicIp',
        'reply_to' => 'getReplyTo',
        'sub_account_id' => 'getSubAccountId',
        'subject' => 'getSubject',
        'submitted_at' => 'getSubmittedAt',
        'text_body' => 'getTextBody',
        'to' => 'getTo',
        'track_clicks' => 'getTrackClicks',
        'track_opens' => 'getTrackOpens'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('amp_body', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('attempt', $data ?? [], null);
        $this->setIfExists('custom_fields', $data ?? [], null);
        $this->setIfExists('email_type', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('groups', $data ?? [], null);
        $this->setIfExists('header_bcc', $data ?? [], null);
        $this->setIfExists('header_cc', $data ?? [], null);
        $this->setIfExists('header_to', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('html_body', $data ?? [], null);
        $this->setIfExists('ip_id', $data ?? [], null);
        $this->setIfExists('ip_pool', $data ?? [], null);
        $this->setIfExists('local_ip', $data ?? [], null);
        $this->setIfExists('message_id', $data ?? [], null);
        $this->setIfExists('pre_text', $data ?? [], null);
        $this->setIfExists('public_ip', $data ?? [], null);
        $this->setIfExists('reply_to', $data ?? [], null);
        $this->setIfExists('sub_account_id', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('submitted_at', $data ?? [], null);
        $this->setIfExists('text_body', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('track_clicks', $data ?? [], null);
        $this->setIfExists('track_opens', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return int|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param int|null $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets amp_body
     *
     * @return string|null
     */
    public function getAmpBody()
    {
        return $this->container['amp_body'];
    }

    /**
     * Sets amp_body
     *
     * @param string|null $amp_body amp_body
     *
     * @return self
     */
    public function setAmpBody($amp_body)
    {
        if (is_null($amp_body)) {
            throw new \InvalidArgumentException('non-nullable amp_body cannot be null');
        }
        $this->container['amp_body'] = $amp_body;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \sendpost\model\Attachment[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \sendpost\model\Attachment[]|null $attachments attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets attempt
     *
     * @return int|null
     */
    public function getAttempt()
    {
        return $this->container['attempt'];
    }

    /**
     * Sets attempt
     *
     * @param int|null $attempt attempt
     *
     * @return self
     */
    public function setAttempt($attempt)
    {
        if (is_null($attempt)) {
            throw new \InvalidArgumentException('non-nullable attempt cannot be null');
        }
        $this->container['attempt'] = $attempt;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        if (is_null($custom_fields)) {
            throw new \InvalidArgumentException('non-nullable custom_fields cannot be null');
        }
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets email_type
     *
     * @return string|null
     */
    public function getEmailType()
    {
        return $this->container['email_type'];
    }

    /**
     * Sets email_type
     *
     * @param string|null $email_type email_type
     *
     * @return self
     */
    public function setEmailType($email_type)
    {
        if (is_null($email_type)) {
            throw new \InvalidArgumentException('non-nullable email_type cannot be null');
        }
        $this->container['email_type'] = $email_type;

        return $this;
    }

    /**
     * Gets from
     *
     * @return \sendpost\model\From|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \sendpost\model\From|null $from from
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets groups
     *
     * @return string[]|null
     */
    public function getGroups()
    {
        return $this->container['groups'];
    }

    /**
     * Sets groups
     *
     * @param string[]|null $groups groups
     *
     * @return self
     */
    public function setGroups($groups)
    {
        if (is_null($groups)) {
            throw new \InvalidArgumentException('non-nullable groups cannot be null');
        }
        $this->container['groups'] = $groups;

        return $this;
    }

    /**
     * Gets header_bcc
     *
     * @return \sendpost\model\CopyTo[]|null
     */
    public function getHeaderBcc()
    {
        return $this->container['header_bcc'];
    }

    /**
     * Sets header_bcc
     *
     * @param \sendpost\model\CopyTo[]|null $header_bcc header_bcc
     *
     * @return self
     */
    public function setHeaderBcc($header_bcc)
    {
        if (is_null($header_bcc)) {
            throw new \InvalidArgumentException('non-nullable header_bcc cannot be null');
        }
        $this->container['header_bcc'] = $header_bcc;

        return $this;
    }

    /**
     * Gets header_cc
     *
     * @return \sendpost\model\CopyTo[]|null
     */
    public function getHeaderCc()
    {
        return $this->container['header_cc'];
    }

    /**
     * Sets header_cc
     *
     * @param \sendpost\model\CopyTo[]|null $header_cc header_cc
     *
     * @return self
     */
    public function setHeaderCc($header_cc)
    {
        if (is_null($header_cc)) {
            throw new \InvalidArgumentException('non-nullable header_cc cannot be null');
        }
        $this->container['header_cc'] = $header_cc;

        return $this;
    }

    /**
     * Gets header_to
     *
     * @return \sendpost\model\To|null
     */
    public function getHeaderTo()
    {
        return $this->container['header_to'];
    }

    /**
     * Sets header_to
     *
     * @param \sendpost\model\To|null $header_to header_to
     *
     * @return self
     */
    public function setHeaderTo($header_to)
    {
        if (is_null($header_to)) {
            throw new \InvalidArgumentException('non-nullable header_to cannot be null');
        }
        $this->container['header_to'] = $header_to;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return object|null
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param object|null $headers headers
     *
     * @return self
     */
    public function setHeaders($headers)
    {
        if (is_null($headers)) {
            throw new \InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets html_body
     *
     * @return string|null
     */
    public function getHtmlBody()
    {
        return $this->container['html_body'];
    }

    /**
     * Sets html_body
     *
     * @param string|null $html_body html_body
     *
     * @return self
     */
    public function setHtmlBody($html_body)
    {
        if (is_null($html_body)) {
            throw new \InvalidArgumentException('non-nullable html_body cannot be null');
        }
        $this->container['html_body'] = $html_body;

        return $this;
    }

    /**
     * Gets ip_id
     *
     * @return int|null
     */
    public function getIpId()
    {
        return $this->container['ip_id'];
    }

    /**
     * Sets ip_id
     *
     * @param int|null $ip_id ip_id
     *
     * @return self
     */
    public function setIpId($ip_id)
    {
        if (is_null($ip_id)) {
            throw new \InvalidArgumentException('non-nullable ip_id cannot be null');
        }
        $this->container['ip_id'] = $ip_id;

        return $this;
    }

    /**
     * Gets ip_pool
     *
     * @return string|null
     */
    public function getIpPool()
    {
        return $this->container['ip_pool'];
    }

    /**
     * Sets ip_pool
     *
     * @param string|null $ip_pool ip_pool
     *
     * @return self
     */
    public function setIpPool($ip_pool)
    {
        if (is_null($ip_pool)) {
            throw new \InvalidArgumentException('non-nullable ip_pool cannot be null');
        }
        $this->container['ip_pool'] = $ip_pool;

        return $this;
    }

    /**
     * Gets local_ip
     *
     * @return string|null
     */
    public function getLocalIp()
    {
        return $this->container['local_ip'];
    }

    /**
     * Sets local_ip
     *
     * @param string|null $local_ip local_ip
     *
     * @return self
     */
    public function setLocalIp($local_ip)
    {
        if (is_null($local_ip)) {
            throw new \InvalidArgumentException('non-nullable local_ip cannot be null');
        }
        $this->container['local_ip'] = $local_ip;

        return $this;
    }

    /**
     * Gets message_id
     *
     * @return string|null
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param string|null $message_id message_id
     *
     * @return self
     */
    public function setMessageId($message_id)
    {
        if (is_null($message_id)) {
            throw new \InvalidArgumentException('non-nullable message_id cannot be null');
        }
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets pre_text
     *
     * @return string|null
     */
    public function getPreText()
    {
        return $this->container['pre_text'];
    }

    /**
     * Sets pre_text
     *
     * @param string|null $pre_text pre_text
     *
     * @return self
     */
    public function setPreText($pre_text)
    {
        if (is_null($pre_text)) {
            throw new \InvalidArgumentException('non-nullable pre_text cannot be null');
        }
        $this->container['pre_text'] = $pre_text;

        return $this;
    }

    /**
     * Gets public_ip
     *
     * @return string|null
     */
    public function getPublicIp()
    {
        return $this->container['public_ip'];
    }

    /**
     * Sets public_ip
     *
     * @param string|null $public_ip public_ip
     *
     * @return self
     */
    public function setPublicIp($public_ip)
    {
        if (is_null($public_ip)) {
            throw new \InvalidArgumentException('non-nullable public_ip cannot be null');
        }
        $this->container['public_ip'] = $public_ip;

        return $this;
    }

    /**
     * Gets reply_to
     *
     * @return \sendpost\model\ReplyTo|null
     */
    public function getReplyTo()
    {
        return $this->container['reply_to'];
    }

    /**
     * Sets reply_to
     *
     * @param \sendpost\model\ReplyTo|null $reply_to reply_to
     *
     * @return self
     */
    public function setReplyTo($reply_to)
    {
        if (is_null($reply_to)) {
            throw new \InvalidArgumentException('non-nullable reply_to cannot be null');
        }
        $this->container['reply_to'] = $reply_to;

        return $this;
    }

    /**
     * Gets sub_account_id
     *
     * @return int|null
     */
    public function getSubAccountId()
    {
        return $this->container['sub_account_id'];
    }

    /**
     * Sets sub_account_id
     *
     * @param int|null $sub_account_id sub_account_id
     *
     * @return self
     */
    public function setSubAccountId($sub_account_id)
    {
        if (is_null($sub_account_id)) {
            throw new \InvalidArgumentException('non-nullable sub_account_id cannot be null');
        }
        $this->container['sub_account_id'] = $sub_account_id;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets submitted_at
     *
     * @return int|null
     */
    public function getSubmittedAt()
    {
        return $this->container['submitted_at'];
    }

    /**
     * Sets submitted_at
     *
     * @param int|null $submitted_at submitted_at
     *
     * @return self
     */
    public function setSubmittedAt($submitted_at)
    {
        if (is_null($submitted_at)) {
            throw new \InvalidArgumentException('non-nullable submitted_at cannot be null');
        }
        $this->container['submitted_at'] = $submitted_at;

        return $this;
    }

    /**
     * Gets text_body
     *
     * @return string|null
     */
    public function getTextBody()
    {
        return $this->container['text_body'];
    }

    /**
     * Sets text_body
     *
     * @param string|null $text_body text_body
     *
     * @return self
     */
    public function setTextBody($text_body)
    {
        if (is_null($text_body)) {
            throw new \InvalidArgumentException('non-nullable text_body cannot be null');
        }
        $this->container['text_body'] = $text_body;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \sendpost\model\To|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \sendpost\model\To|null $to to
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets track_clicks
     *
     * @return bool|null
     */
    public function getTrackClicks()
    {
        return $this->container['track_clicks'];
    }

    /**
     * Sets track_clicks
     *
     * @param bool|null $track_clicks track_clicks
     *
     * @return self
     */
    public function setTrackClicks($track_clicks)
    {
        if (is_null($track_clicks)) {
            throw new \InvalidArgumentException('non-nullable track_clicks cannot be null');
        }
        $this->container['track_clicks'] = $track_clicks;

        return $this;
    }

    /**
     * Gets track_opens
     *
     * @return bool|null
     */
    public function getTrackOpens()
    {
        return $this->container['track_opens'];
    }

    /**
     * Sets track_opens
     *
     * @param bool|null $track_opens track_opens
     *
     * @return self
     */
    public function setTrackOpens($track_opens)
    {
        if (is_null($track_opens)) {
            throw new \InvalidArgumentException('non-nullable track_opens cannot be null');
        }
        $this->container['track_opens'] = $track_opens;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


